# Generated by Django 4.2.6 on 2023-10-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('display_photo', models.ImageField(upload_to='display_photo/')),
                ('about_photo', models.ImageField(upload_to='about_photo/')),
                ('body', models.TextField()),
                ('city', models.CharField(default=False, max_length=30)),
                ('country', models.CharField(default=False, max_length=30)),
                ('phone_number', models.CharField(default=False, max_length=16)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('github_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
