# Generated by Django 4.2.6 on 2023-10-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_about_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
