# Generated by Django 4.2.6 on 2023-10-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='projects/')),
                ('web_url', models.URLField(blank=True, max_length=100, null=True)),
                ('github_url', models.URLField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('contributions', 'Contributions')], default='personal', max_length=15)),
            ],
        ),
    ]
